version: "2.2"

services:
    redis:
        image: redis

    manager:
        build: container_manager
        ports:
            - "8000:80"
        volumes:
            - ./configuracao:/config
        links:
            - eventos
            - lbeventos
        depends_on: 
            - lbeventos
            - lbconsulta

    lbconsulta:
        image: dockercloud/haproxy
        depends_on:
            - consulta
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - ADDITIONAL_SERVICES=streamdbmiddleware:consulta


    lbeventos:
        image: dockercloud/haproxy
        depends_on:
            - eventos
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - ADDITIONAL_SERVICES=streamdbmiddleware:eventos
        

    eventos:
        scale: 1
        build: container_eventos
        #ports:
        #    - "8001:80"
        volumes:
            - ./configuracao:/config
        links:
            - lbconsulta
            - consulta
        depends_on:
            - lbconsulta
            - consulta

    consulta:
        scale: 2
        build: container_consulta
        volumes:
            - ./configuracao:/config
        links:
            - redis      
            
    webui:
        build: webui
        ports: 
            - 8080:80
        volumes:
            - ./configuracao:/config
        links:
            - redis      
