redis:
    image: redis

manager:
    build: container_manager
    ports:
        - "8000:80"
    volumes:
        - ./configuracao:/config

eventos:
    build: container_eventos
    ports:
        - "8001:80"
    volumes:
        - ./configuracao:/config

consulta:
    build: container_consulta
    ports:
        - "8002:80"
    volumes:
        - ./configuracao:/config
    links:
        - redis
