version: "3"

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/bin/docker
      # SSH directory
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/devcontainer/.ssh
      # Git config
      - ~/.gitconfig:/root/.gitconfig
      - ~/.gitconfig:/home/devcontainer/.gitconfig
    environment:
      - TZ=
    entrypoint: zsh -c "while sleep 1000; do :; done"