version: "2.2"

services: 
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf:ro
    expose:
      - 3306
    ports:
      - 3306:3306      
    environment:
      MYSQL_ROOT_PASSWORD: password

  alimenta_db:
    build : .
    depends_on: 
      - db
    



